# Generated by Django 6.1.1 on 2026-09-09 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("standard_code", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_statement",
                    models.TextField(
                        default="This Gangway / Platform has been visually inspected in conformity with NEN-EN 526 and approved for use for the period of one year."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NDTReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        help_text="e.g. MTQ-PR017Rev00", max_length=100, unique=True
                    ),
                ),
                ("vessel_name", models.CharField(max_length=200)),
                (
                    "project_no",
                    models.CharField(help_text="MTQ Project No.", max_length=100),
                ),
                (
                    "make_manufacturer",
                    models.CharField(default="MTQ Products B.V.", max_length=200),
                ),
                ("year_manufactured", models.CharField(blank=True, max_length=50)),
                (
                    "size_length",
                    models.CharField(
                        blank=True, help_text="Size/length in meters", max_length=100
                    ),
                ),
                ("marking_tag", models.CharField(blank=True, max_length=100)),
                ("inspection_date", models.DateField()),
                ("validity_until", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved / Passed"),
                            ("REJECTED", "Failed"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                (
                    "approval_statement",
                    models.TextField(
                        default="This Gangway / Platform has been visually inspected in conformity with NEN-EN 526 and approved for use for the period of one year."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional observations or remarks"
                    ),
                ),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("LIVE", "Live Signature Canvas"),
                            ("UPLOADED", "Uploaded Signature File"),
                            ("SAVED", "Saved Profile Signature"),
                        ],
                        default="LIVE",
                        max_length=20,
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures/reports/"
                    ),
                ),
                (
                    "stamp_image",
                    models.ImageField(blank=True, null=True, upload_to="stamps/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="home.inspectionprocedure",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin / Technical Supervisor"),
                            ("INSPECTOR", "Testing Person / Inspector"),
                        ],
                        default="INSPECTOR",
                        max_length=20,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        default="ISO 9712 NDT Inspector Level II",
                        max_length=150,
                    ),
                ),
                (
                    "certification_no",
                    models.CharField(blank=True, default="CERT-99201", max_length=100),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="MTQ Products B.V.", max_length=150
                    ),
                ),
                (
                    "profile_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="signatures/profiles/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
